### Poista henkilö id:llä
DELETE http://localhost:3001/api/persons/6864d0e5a03db236f5795557

### Hae kaikki henkilöt
GET http://localhost:3001/api/persons

### Lisää uusi henkilö
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Uusi_nimi",
  "number": "123-456789"
}

### Lisää henkilö ilman nimeä
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "123-456789"
}

### Lisää henkilö ilman numeroa
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Pelkkä Nimi"
}

### Lisää henkilö, jonka nimi on jo listalla
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "000-000000"
}

### Lisää henkilö Testi Testinen
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Testi Testinen",
  "number": "040-9999999"
}

### Päivitä olemassa oleva henkilö
PUT http://localhost:3001/api/persons/686b86eb470f82dc08a4277e
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "999-9999999"
}
